---
- name: configuration directories
  file: state=directory dest={{ item }} mode=0755
  with_items:
  - "{{ nginx_config_dir }}"
  become: yes

- name: install certbot (letsencrypt)
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/local/bin/certbot-auto
    mode: 755

- name: SSL credentials with certbot (letsencrypt)
  command: /usr/local/bin/certbot-auto certonly --agree-tos --standalone -m {{ letsencrypt_email }} -d {{ inventory_hostname }} creates=/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
  become: yes
  notify:
  - reload nginx configuration

- name: Setup letsencrypt renewal with cron
  copy: src=letsencrypt-renew dest=/etc/cron.daily/letsencrypt-renew mode=0755
  become: yes

- name: nginx configuration
  template: src=nginx.conf.j2 dest={{ nginx_config_dir }}/nginx.conf mode=0644
  become: yes
  notify:
  - reload nginx configuration

- name: copy the Dockerfile to the nginx configuration directory
  template: src=Dockerfile_nginx.j2 dest={{ nginx_config_dir }}/Dockerfile mode=0644
  become: yes

- name: build tmpnb nginx image
  docker_image:
    path: "{{ nginx_config_dir }}"
    name: tmpnb_nginx
    state: present
  become: yes
 
- name: launch nginx
  docker:
    image: tmpnb_nginx
    state: running
    name: nginx
    volumes: "{{ nginx_volumes }}"
    ports: "{{ nginx_ports }}"
    restart_policy: always
