---
ssl_cert_path: /etc/ssl/tmpnb.org.crt
ssl_key_path: /etc/ssl/tmpnb.org.key
static_path: /var/www/nature-demo
user_static_files: /srv/ipython/IPython/html/static
nginx_config_dir: /etc/nginx
nginx_volumes:
- "{{ nginx_config_dir }}/nginx.conf:/etc/nginx/nginx.conf:ro"
- "{{ ssl_key_path }}:{{ ssl_key_path }}:ro"
- "{{ ssl_cert_path }}:{{ ssl_cert_path }}:ro"
nginx_ports:
- 80:80
- 443:443