---
- name: install vim for ops sanity
  apt: update_cache=yes cache_valid_time=600 name=vim state=latest
  sudo: yes

- name: YOLO system upgrade
  apt: upgrade=safe
  sudo: yes

- name: sshd configuration
  copy: src=sshd_config dest=/etc/ssh/sshd_config mode=0644
  sudo: yes
  notify:
  - restart sshd

- name: directory to hold public keys
  file: state=directory path=/tmp/pubkeys mode=0755

- name: fetch public keys from github
  get_url: dest=/tmp/pubkeys/{{ item }}-pubkeys url=https://github.com/{{ item }}.keys
  with_items: github_usernames

- name: assemble the authorized keys file
  assemble: dest=/root/.ssh/authorized_keys mode=0600 src=/tmp/pubkeys
  sudo: yes
